Repository react-native-netinfo/react-native-netinfo, pull requests merged in 2021-11, with the labels that each got.

#436 [feat] Add 5g cellular type
  android/gradle.properties
  android/src/main/java/com/reactnativecommunity/netinfo/types/CellularGeneration.java
  ios/RNCConnectionState.h
  ios/RNCConnectionState.m
  src/__tests__/fetch.spec.ts
  src/internal/types.ts
Labels: pending merge

#510 Update NetworkCallbackConnectivityReceiver.java
  android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java
Labels: question, android, pending merge

#522 test(example): use cross-platform path style
  package.json
  react-native.config.js
Labels: awaiting info, pending merge

#527 style(example): fix scrollview jitter in example app
  example/index.tsx
Labels: pending merge

#544 fix(web, isConnected): Return actual connection state even if network type is 'unknown'
  README.md
  src/internal/nativeModule.web.ts
  src/internal/types.ts
Labels: pending merge
