Repository react-native-netinfo/react-native-netinfo, pull requests merged in 2023-11, with the labels that each got.

#680 Fixed Typeerror for addvenetlistner added isWifiEnabled type in NetInfoUnknownState and NetInfoDisconnectedState
  src/internal/types.ts
Labels: pending merge

#673 feat: add HTTP headers through reachabilityHeaders param to NetInfoConfiguration
  README.md
  src/internal/defaultConfiguration.ts
  src/internal/defaultConfiguration.web.ts
  src/internal/internetReachability.ts
  src/internal/types.ts
Labels: pending merge

#692 feat(android)!: specify export mode on BroadcastReceivers, requires compileSdk 33+
  android/gradle.properties
  android/src/main/java/com/reactnativecommunity/netinfo/AmazonFireDeviceConnectivityPoller.java
  android/src/main/java/com/reactnativecommunity/netinfo/BroadcastReceiverConnectivityReceiver.java
  android/src/main/java/com/reactnativecommunity/netinfo/NetInfoUtils.java
Labels: awaiting info, pending merge

#700 fixed abort pending request of internetReachability
  src/internal/internetReachability.ts
Labels: changes requested
